# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18801afe96ed91a406c8dab5dda25f8f2362229b2af2abbd17906ce22183bdc822fddf5def021da0f73cbdab7aadbdeaa105ef5cb5fdacd1acb3269cc9e64104

test:
  secret_key_base: e4bf8b2d42e367b6aa4127a69f516ade8287d5757f0f6b53b35824f19f2899e753161302232b4261611e2073666ae07bcbb3d770dd45942bd54afd34ca8f8109

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
